site_name: mappMotion samples
use_directory_urls: false

extra_css: [extra.css]
    
nav:
  - Start: index.md
  - Python Installation: installation.md
  - References:
    - Synchronous motor table conversion: refs/refs_motor_conv_sync.md
    - Induction motor table conversion: refs/refs_motor_conv_ind.md
  - Revision: revision.md

theme:
    name: material
    logo: images/bur.png

    palette:
      scheme: default
      primary: orange
      accent: orange

    features: toc.integrate

plugins:
  - search

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
      
repo_url: https://github.com/br-automation-com/mappMotion-Samples
repo_name: GitHub Repo

